refine admin guide ja
opst/knitfab pull request #146
Opened 2024-08-29 07:10 UTC by hideo-terada-opst

- 文体を「ですます」調に変更
- セクション番号の付与
- 実際にこのドキュメントに沿ってインストールしてみて、分かりにくかった表現を改善
- ファイルを２つのパートに分割
- 目次の追加
- その他細かな文章表現の修正

2024-08-29 08:35 UTC, takaoka-youta-opst requested changes
文末の訂正漏れをいくらか見つけました。

また、ファイル名については次のように変更することを提案します。

- `admin-guide-part1.ja.md` => `admin-guide-installing.ja.md`
- `admin-guide-part2.ja.md` => `admin-guide-deep-dive.ja.md`

ユーザはファイル名だけ見てどのドキュメントを読むか選ぶでしょうから、ドキュメントの射程範囲がファイル名に見えた方が良いのではないか、と考えます。

2024-08-29 08:35 UTC, takaoka-youta-opst commented on docs/03.admin-guide/admin-guide-part1.ja.md
> +<!-- End of Part1-->
コメントの削除漏れ？

2024-08-29 23:44 UTC, hideo-terada-opst commented on .tours/brushup-admin-guide-ja.tour
> +{
codetour 試していたのを忘れてました。
そもそも、対象のファイル名を変更したので意味なくなってますね。
削除します。

2024-08-29 23:44 UTC, hideo-terada-opst commented on docs/03.admin-guide/admin-guide-part1.ja.md
> +<!-- TODO: インストールの成否はどうやって確認するか記載 -->
このTODOは、ユーザが見ると不安になると思うので、修正します。

2024-08-29 23:55 UTC, hideo-terada-opst commented on docs/03.admin-guide/admin-guide-part2.ja.md
> +`admin-tools/restore/images.sh` を実行すると、次のように表示される。
修正しました。

2024-08-30 00:59 UTC, hideo-terada-opst commented on docs/03.admin-guide/admin-guide-part2.ja.md
> +ければ、`y` を入力して enter する。
修正します。

2024-08-30 01:58 UTC, hideo-terada-opst commented on .tours/brushup-admin-guide-ja.tour
> +{
ファイル名については、私も同様のことが頭をよぎったのですが、とりあえずパート番号にしてみました。
特に深い意味はないので、提案を採用したいと思います。

2024-08-30 01:59 UTC, hideo-terada-opst commented on .tours/brushup-admin-guide-ja.tour
> +{
-installation.ja.md という名詞形にしようと思います。

2024-08-30 02:16 UTC, hideo-terada-opst commented on docs/03.admin-guide/admin-guide-part1.ja.md
> +4. ユーザにハンドアウトを配布し、利用開始してもらう。
修正しました。

2024-08-30 02:16 UTC, hideo-terada-opst commented on docs/03.admin-guide/admin-guide-part1.ja.md
> +<!-- End of Part1-->
修正しました。

2024-08-30 02:29 UTC, hideo-terada-opst commented
修正をPUSHしたので、再度レビュー願います。

2024-08-30 04:50 UTC, takaoka-youta-opst commented on docs/03.admin-guide/admin-guide-installation.ja.md
> +$ kubectl get deploy -A
- `-A` だと、Knitfab に直接関係していない namespace のものも見えてしまいますよね。これは意図的ですか？

2024-08-30 04:53 UTC, takaoka-youta-opst commented on docs/03.admin-guide/admin-guide-installation.ja.md
> +-----------------------
この `--------...` は、 github の markdown processer によって `<hr>` として解釈されています。

見出しを `<h2>` 相当にしたいなら、

- 見出し文の行頭を `#` ではなくて `##` にし、この `---...` を取り除く

もしくは、

- 見出し文冒頭の `#` を取り除く

のいずれかの対処が必要です。

2024-08-30 04:55 UTC, hideo-terada-opst commented on docs/03.admin-guide/admin-guide-installation.ja.md
> +$ kubectl get deploy -A
はい、意図的です。できるだけコマンドの文字数を少なくしたいからです。
初級ユーザーが感じるであろうCLI操作上の負担感を少しでも減らしと思っています。

2024-08-30 04:56 UTC, hideo-terada-opst commented on docs/03.admin-guide/admin-guide-installation.ja.md
> +-----------------------
見出しは H1にしたい意図ですが、

2024-08-30 05:06 UTC, hideo-terada-opst commented on docs/03.admin-guide/admin-guide-installation.ja.md
> +$ kubectl get deploy -A
名前空間を指定する例も記載することにしました。

2024-08-30 05:10 UTC, hideo-terada-opst commented
修正しました。確認願います。

2024-08-30 07:01 UTC, takaoka-youta-opst approved these changes
LGTM

2024-08-30 07:01 UTC, merged