Creat an English translation of admin-guide.
opst/knitfab pull request #16
Opened 2024-04-01 10:01 UTC by ogawatsukasaopst

## This PR
Creat an English translation of admin-guide.
In addition, slightly modifi the origin.

## Corresponding issue

- #1

2024-04-03 01:59 UTC, takaoka-youta-opst approved these changes

2024-04-03 02:01 UTC, takaoka-youta-opst commented on docs/03.admin-guide/admin-guide.en.md
> +```
ここに最近変更がありました。追従をお願いします。

2024-04-03 02:01 UTC, takaoka-youta-opst commented on docs/03.admin-guide/admin-guide.en.md
> +./installer.sh --kubeconfig path/to/kubeconfig -n NAMESPACE -s ./Knitfab-install-settings
ここに最近変更がありました。追従をお願いします。

2024-04-04 00:23 UTC, ogawatsukasaopst commented on docs/03.admin-guide/admin-guide.en.md
> +```
```suggestion
```
./installer.sh --prepare --kubeconfig ${YOUR_KUBECONFIG}
```
```
変更後の内容はこちらでよろしいでしょうか？

2024-04-04 00:24 UTC, ogawatsukasaopst commented on docs/03.admin-guide/admin-guide.en.md
> +```
```suggestion

./installer.sh --prepare --kubeconfig ${YOUR_KUBECONFIG}

```
こちらでよろしいでしょうか？

2024-04-04 00:25 UTC, ogawatsukasaopst commented on docs/03.admin-guide/admin-guide.en.md
> +./installer.sh --kubeconfig path/to/kubeconfig -n NAMESPACE -s ./Knitfab-install-settings
```suggestion
./installer.sh --install --kubeconfig path/to/kubeconfig -n NAMESPACE -s ./knitfab-install-settings
```
こちらでよろしいでしょうか？

2024-04-04 00:49 UTC, takaoka-youta-opst requested changes
Follow #45

2024-04-04 01:00 UTC, ogawatsukasaopst commented on docs/03.admin-guide/admin-guide.en.md
> +- Kubernetes Cluster: Knitfab runs on Kubernetes.
```suggestion
- Kubernetes Cluster consisting of Nodes equipped with x86_64 CPUs: Knitfab runs Kubernetes.
```
こちらに変更する予定です。

2024-04-04 02:44 UTC, takaoka-youta-opst approved these changes

2024-04-04 02:45 UTC, merged